app:
  version: "0.0.1"
  env: "local"
  name: "酷社区"
  desc: "酷社区"
  keywords: "酷社区"
  visitMode: "guest" # 访问模式 auth-需登录才能访问 guest-无需登录访问
session:
  name: "ku-bbs"
  secret: "123456"
db:
  host: "127.0.0.1"
  port: "3306"
  name: "root"
  pass: ""
  db: "ku-bbs"
redis:
  host: "127.0.0.1"
  pass: ""
  port: "6379"
  db: "1"
  idleTimeout: "10"
upload:
  path: "../assets/upload"
  imageExt: [ "png", "jpg", "jpeg", "gif" ]
  avatarFileSize: 1 # 单位 M
  topicFileSize: 2 # 单位 M
